### ISSUE TITLE
2024.10.25 testing issues

### ISSUE THREAD

**Issue by xcolwell** [urnetwork/android#180]
Below are the issues with testing the 2024.10.25 release for Android. It was tested on 22 phones (Android 7-15), 3 tablets (10", 7"), 1 Chromebook, and 1 TV. The issues are organized by importance.

Critical

- [x] Older devices crash with too large bitmaps. The BG bitmaps were updated to larger widths causing crashed on older devices whenever a full bleed background is shown, e.g. login interstitial. It looks like older devices can't render bitmaps above 1600px in any dimension, and crash with an error like `java.lang.RuntimeException: Canvas: trying to draw too large(268435456bytes) bitmap.`

Priority

- [ ] Drawer scrolling issues. Drawer sometimes closes instead of scrolling to the top. See video. The expected behavior is the drawer always scrolls to the top before closing. Tapping on a location also always closes the drawer, even if the location is already selected. Pulling down from the very top always closes the drawer. [^1]
- [x] On welcome interstitial, can't tap Enter button on small screens or in landscape mode.
- [x] Welcome interstitial jumps in size on start of animation, leading to a non-smooth animation.

Minor

- [x] Initial login screen elements are not centered on tablets
- [ ] Welcome interstitial on landscape mode, on large screens the edges of the mask are visible leading to a glitchy appearance. The mask size needs to be increased ~1000px on both dimensions.
- [ ] Welcome interstitial on landscape mode, the connector image is not centered.

[^1]: https://github.com/user-attachments/assets/de2eb823-6713-4484-b83f-cd302d86ff12  (see how it should be scrolling to the top, but instead it's catching and resizing the tray)

**Comment by stuartwk** [comment]
The scrolling bug looks to be a Jetpack Compose issue that is being tracked https://issuetracker.google.com/issues/353304855
